### ISSUE TITLE
env: node\r: No such file or directory

### ISSUE THREAD

**Issue by et** [srph/npm-scripts-info#13]
Hi 👋 

I was using the [typescript starter project](https://github.com/bitjson/typescript-starter/issues/70) and was getting the error `env: node\r: No such file or directory` when I tried to run `npm-scripts-info`.

You can read that thread for the details so I won't duplicate them here.
I was just wondering if you had seen this error before as it seems to be isolated to `npm-scripts-info`.

If you haven't seen this before, feel free to close as I realize this isn't the most helpful bug report 😞.

Thanks!

**Comment by srph** [comment]
I'll take a look :D. If you have any idea, that'd be great. Thanks for reporting!

**Comment by codeNoobie** [comment]
@srph I am experiencing this issue as well. Would you be able to help with this? :)

**Comment by iyuuya** [comment]
I think related this issue https://github.com/npm/npm/issues/2097

**Comment by bitjson** [comment]
Wanted to get this working again for [typescript-starter](https://github.com/bitjson/typescript-starter/issues/70) (as mention by @et above), so I just published a version that works on Linux and macOS: [`@bitjson/npm-scripts-info`](https://www.npmjs.com/package/@bitjson/npm-scripts-info)

To install, just:

```sh
yarn remove --save npm-scripts-info
yarn add --dev @bitjson/npm-scripts-info
```

Or for npm:

```sh
npm rm --save npm-scripts-info
npm install --save-dev @bitjson/npm-scripts-info
```

No other changes necessary (it's really just a fork with the package name and version updated, published without the CRLF issue).

**Comment by et** [comment]
Thanks @bitjson. Any chance you could submit a PR for @srph to pull in?

**Comment by bitjson** [comment]
I'm afraid the issue is that @srph is publishing from Windows. All I did was change the package name and mark it as `v1.0.0` (since I think this project is plenty stable enough for SemVer now).

@srph if you'd like (and you trust me 😅) I'd be happy to publish it to your NPM project. You'd just have to add me with `npm owner add jasondreyzehner npm-scripts-info`.

**Comment by bitjson** [comment]
Alternatively, you could probably set up automatic publishing from a trusted CI environment, which would usually then be publishing from Linux.

**Comment by elektronik2k5** [comment]
I'm on Linux and it works with npm just fine. Doesn't with yarn :/
Here's my workaround, assuming you're on recent version of `npm`, which includes `npx`:
```shell
npx npm-scripts-info
```

**Comment by srph** [comment]
I just published `v0.3.9` from OSX. Can anyone check if it's working nicely? cc @bitjson 

I've been busy the past few months. Apologies for not being able to reply soonest :(

**Comment by srph** [comment]
@elektronik2k5. Nice workaround. What seems to be the issue with yarn? Feel free to submit a separate issue 😄.

Closing this because it _seems_ to work fine now. But feel free to leave a comment or reopen if not ;).

**Comment by elektronik2k5** [comment]
I can confirm that the latest version works fine in yarn. :)

**Comment by srph** [comment]
Thank you @elektronik2k5 :)
