### ISSUE TITLE
Improve output

### ISSUE THREAD

**Issue by srph** [srph/npm-scripts-info#3]
Current output looks bad.

![screen shot 2016-02-20 at 7 54 41 pm](https://cloud.githubusercontent.com/assets/5093058/13196551/e168ab08-d80b-11e5-9487-d4df41514769.png)

**Comment by rafaelrinaldi** [comment]
First of all thanks for this! I've been tempted to start a project just like it and then stumbled upon yours. It's really helpful for when you have lots of scripts.

So, I was thinking about following the "reporters" approach that most test runners use. Something like:

``` json
{
  "scripts": {
    "info": "npm-scripts-info --reporter custom.js"
  }
}
```

``` js
var myThing = require('my-thing');

module.exports = function(input) {
  return myThing(input);  
};
```

Something around these lines. Then we can have "official" reporters like "table" and so on.

Thoughts?

**Comment by srph** [comment]
Interesting input. I'll catch up after work.

**Comment by srph** [comment]
I took a shot, check #4

**Comment by rafaelrinaldi** [comment]
@srph That's exactly what I had in mind. Makes custom output way more flexible.

Good job! :tada:
