### ISSUE TITLE
Allow the JavaScript API to accept a package.json obect

### ISSUE THREAD

**Issue by zkochan** [srph/npm-scripts-info#8]
Currently npm-scripts-info automatically loads the package json from the current working directory. This makes the module not reusable.

This change will allow to write a [mos](https://github.com/zkochan/mos) plugin for generating scripts documentation sections

I can make a pull request today with this update

**Comment by srph** [comment]
Whoa, sure, thanks! :tada:

Been busy lately at work.

**Comment by zkochan** [comment]
You're welcome :smile: 

It appeared to be pretty simple to do
